---
title: " 2022 casual BikeShare Data Analysis"
author: "Naida Torres, Claudia LaPlant, ...."
date: "2023-12-04"
output: html_document
---

```{r}
library(here)
library(janitor)
library(tidyverse)
library(openmeteo)
library(ggplot2)
library(plotly)
```


```{r}

dfJan = read_csv(here("data_raw", "202201-capitalbikeshare-tripdata.zip")) %>% clean_names()
 

dfFeb = read_csv(here("data_raw", "202202-capitalbikeshare-tripdata.zip")) %>% clean_names()
 

dfMar = read_csv(here("data_raw", "202202-capitalbikeshare-tripdata.zip")) %>% clean_names()
 

dfApril = read_csv(here("data_raw", "20224-capitalbikeshare-tripdata.zip")) %>% clean_names()
 

dfMay = read_csv(here("data_raw", "202205-capitalbikeshare-tripdata.zip")) %>% clean_names()
 

dfJune = read_csv(here("data_raw", "202206-capitalbikeshare-tripdata.zip")) %>% clean_names()
 

dfJuly = read_csv(here("data_raw", "202207-capitalbikeshare-tripdata.zip")) %>% clean_names()

dfAug = read_csv(here("data_raw", "202208-capitalbikeshare-tripdata.zip")) %>% clean_names()

dfSep = read_csv(here("data_raw", "202209-capitalbikeshare-tripdata.zip")) %>% clean_names()

dfOct = read_csv(here("data_raw", "2022010-capitalbikeshare-tripdata.zip")) %>% clean_names()

dfNov = read_csv(here("data_raw", "202211-capitalbikeshare-tripdata.zip")) %>% clean_names()

dfDec = read_csv(here("data_raw", "202212-capitalbikeshare-tripdata.zip")) %>% clean_names()
```

```
filtering the full list of riders for the year of 2022 to only include the riders who are listed as casual members for each month.

```{r}


```

